### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by feurize** [E-boi/replugged-plugins#6]
### Console log upon opening the plugin option screen:
Replugged version: 4.5.0
OS: Windows 11 x64
Discord version: Stable 210566 (fc3ede1)

```js
TypeError: Cannot read properties of undefined (reading 'map')
    at Fe (renderer.js?t=1688264196416}:1:9116)
    at Sa (7127162bcec2aa26c395.js:1784:54)
    at gu (7127162bcec2aa26c395.js:1838:146)
    at Ic (7127162bcec2aa26c395.js:1831:89)
    at mc (7127162bcec2aa26c395.js:1831:17)
    at hc (7127162bcec2aa26c395.js:1830:867)
    at oc (7127162bcec2aa26c395.js:1827:642)
    at uc (7127162bcec2aa26c395.js:1828:49)
    at Fi (7127162bcec2aa26c395.js:1767:577)
    at lc (7127162bcec2aa26c395.js:1828:498)
    at t.flushSync (7127162bcec2aa26c395.js:1850:496)
    at o.toggleShow (7127162bcec2aa26c395.js:2856:67)
    at o.hide (7127162bcec2aa26c395.js:2855:853)
    at e.handleClick (7127162bcec2aa26c395.js:2853:726)
    at Object.Me (7127162bcec2aa26c395.js:1736:509)
    at je (7127162bcec2aa26c395.js:1736:663)
    at 7127162bcec2aa26c395.js:1757:416
    at Ur (7127162bcec2aa26c395.js:1757:513)
    at Gr (7127162bcec2aa26c395.js:1757:927)
    at 7127162bcec2aa26c395.js:1763:415
    at cc (7127162bcec2aa26c395.js:1828:267)
    at Le (7127162bcec2aa26c395.js:1735:624)
    at Yr (7127162bcec2aa26c395.js:1759:232)
    at Kt (7127162bcec2aa26c395.js:1742:858)
    at Zt (7127162bcec2aa26c395.js:1742:642)
    at HTMLDivElement.r (12d78f8773542cb393ed.js:244:271)
```
and

```js
[Replugged:Components:ErrorBoundary] ErrorBoundary caught an error TypeError: Cannot read properties of undefined (reading 'map')
    at Fe (renderer.js?t=1688264196416}:1:9116)
    at Sa (7127162bcec2aa26c395.js:1784:54)
    at gu (7127162bcec2aa26c395.js:1838:146)
    at Ic (7127162bcec2aa26c395.js:1831:89)
    at mc (7127162bcec2aa26c395.js:1831:17)
    at hc (7127162bcec2aa26c395.js:1830:867)
    at oc (7127162bcec2aa26c395.js:1827:642)
    at uc (7127162bcec2aa26c395.js:1828:49)
    at Fi (7127162bcec2aa26c395.js:1767:577)
    at lc (7127162bcec2aa26c395.js:1828:498)
    at t.flushSync (7127162bcec2aa26c395.js:1850:496)
    at o.toggleShow (7127162bcec2aa26c395.js:2856:67)
    at o.hide (7127162bcec2aa26c395.js:2855:853)
    at e.handleClick (7127162bcec2aa26c395.js:2853:726)
    at Object.Me (7127162bcec2aa26c395.js:1736:509)
    at je (7127162bcec2aa26c395.js:1736:663)
    at 7127162bcec2aa26c395.js:1757:416
    at Ur (7127162bcec2aa26c395.js:1757:513)
    at Gr (7127162bcec2aa26c395.js:1757:927)
    at 7127162bcec2aa26c395.js:1763:415
    at cc (7127162bcec2aa26c395.js:1828:267)
    at Le (7127162bcec2aa26c395.js:1735:624)
    at Yr (7127162bcec2aa26c395.js:1759:232)
    at Kt (7127162bcec2aa26c395.js:1742:858)
    at Zt (7127162bcec2aa26c395.js:1742:642)
    at HTMLDivElement.r (12d78f8773542cb393ed.js:244:271) 
```

**Comment by feurize** [comment]
If you need more details, lmk.

**Comment by E-boi** [comment]
Which plugin is this happening on?
